### ISSUE TITLE
Inquiry About Parameter Significance and Effect on Prediction Results

### ISSUE THREAD

**Issue by NgdHung31** [ChenyiZhang007/Click2Trimap#2]
Hello,

First of all, I would like to congratulate you on your impressive paper and GitHub project! Your work is very inspiring and provides valuable insights into the field.

I am reaching out to inquire about the parameters used in the code, specifically those shown in the image attached. I am particularly interested in understanding the significance of these parameters:

- `use_zoom_in`
- `fixed_crop`
- `skip_clicks`
- `target_size`
- `expansion_ratio`
- `net_clicks_limit`
- `brs_mode`
- `prob_thresh`
- `lbfgs_max_iters`
- `alpha_blend`
- `click_radius`

Additionally, I would like to know how the argument `args.limit_longest_size` affects the prediction results. I couldn't find detailed explanations of these parameters in the paper, and any clarification on their roles would be greatly appreciated.

Thank you for your time, and I look forward to your response!
![image](https://github.com/user-attachments/assets/aca99655-0d9c-4527-ad2c-10e69ac600db)

**Comment by ChenyiZhang007** [comment]
Thank you for your interest in our work. Our demo is mainly modified from [SimpleClick](https://github.com/uncbiag/SimpleClick) and [RITM,](https://github.com/SamsungLabs/ritm_interactive_segmentation), so there are some parameters and settings related to interactive segmentation that we haven't removed. For simplicity, we actually removed some functions directly in the code, such as zoom in. As for the specific meaning of each parameter, you can refer to these two repositories and their corresponding papers. In particular, the parameter `args.limit_longest_size` has no practical significance, and we apologize for forgetting to remove it, causing you confusion. In the first stage of inference, the resolution for Click2Trimap is fixed at 448, and in the second stage, it is fixed at the original image resolution. You can verify this in debug mode.
